### PR TITLE
Workaround to launch appimages from a sandboxed appimage

### LINKED ISSUE #16: [Feature request] Allow a sandboxed AppImage to launch other AppImages
Hello, I've recently came across [runimage](https://github.com/VHSgunzo/runimage) which is a portable container that uses bubblewrap and it is capable of launching appimages without issues unlike other similar solutions like conty. 

I contacted the developer and the reason it can do so is because it uses the `--cap-add ALL` flag with bubblewrap, but the issue of the appimages would be fixed by just adding the `CAP_SYS_ADMIN` capability. 

What do you think of doing this? Any downsides? If they are what about making that an option instead similar to the sandbox levels.

--------------------------------------------------------------

Also firefox web-browsers are not able to create their own sandbox under bwrap as [pointed out here](https://librewolf.net/installation/linux/#security) and enabling capabilities would allow for it to work under aisap.

### PR DESCRIPTION
**Pull request by Samueru-sama**
Hello, I think this is all that's needed to fix #16 in the meantime without having to do stuff like use a patched bubblewrap.

### CODE REVIEW

**Comment by mgord9518** [comment]
Couldn't this have side-effects for the AppImage being sandboxed, like if it were to launch differently if it thought it was being extracted? I can't think of any examples but it seems like a possibility 

Would it be possible for you to set this environment variable inside your application instead of directly in aisap? I'd like aisap to move away from these hard-coded environment variables, at least by default

**Comment by Samueru-sama** [comment]
> Couldn't this have side-effects for the AppImage being sandboxed, like if it were to launch differently if it thought it was being extracted? I can't think of any examples but it seems like a possibility

`APPIMAGE_EXTRACT_AND_RUN` is only used by the appimage runtime to self extract and run, which aisap already bypasses all together mounting the appimage manually with its own squashfuse, aka it is the equivalent of adding `APPIMAGE_EXTRACT_AND_RUN` to the `AppRun` of an appimage, has no effect on the appimage itself and only on subsequent appimages that would be launched by the application, which would fail to launch anyway without this variable.

> Would it be possible for you to set this environment variable inside your application instead of directly in aisap? 

How? the var has to be set after the appimage is mounted unless aisap has a way to pass env variables to the application without affecting aisap itself?

**Comment by mgord9518** [comment]
@Samueru-sama I mean having the AppImage check if it's in a sandbox, then set APPIMAGE_EXTRACT_AND_RUN for whatever other AppImage it's trying to launch

I know it'll have no effect over the runtime of the first AppImage (as it isn't used), but it's certainly possible that an application could check if APPIMAGE_EXTRACT_AND_RUN is set inside the AppRun, then change behavior (ie store config or something inside the appdir)

If there's no other solution I'm not opposed to adding it, but it should probably be behind an environment variable, something like AISAP_SET_APPIMAGE_EXTRACT_AND_RUN since its usecases are fairly niche

**Comment by Samueru-sama** [comment]
> @Samueru-sama I mean having the AppImage check if it's in a sandbox, then set APPIMAGE_EXTRACT_AND_RUN for whatever other AppImage it's trying to launch

The issue with that is that I would need to do apply that change to all the appimages that I sandbox, that is I would need to extract all those appimages and add the var in their respective AppRuns, this is a not feasible and would also break updates with appimageupdatetool unless I also re-embed the update information when turning all the extracted appimages back.

And all of that would need to be redone after the app updates.

Unfortunately I have stuff like `dunst`, `rofi`, `zenity` and `playerctl` as appimages, and a lot of applications interact with them.

> I know it'll have no effect over the runtime of the first AppImage (as it isn't used), but it's certainly possible that an application could check if APPIMAGE_EXTRACT_AND_RUN is set inside the AppRun, then change behavior (ie update in a different fashion) then break before it won't have write access to its own files

Never seen such a thing, and also seems very impractical because the appimage could be launched with the `--appimage-extract-and-run` flag instead which doesn't use the variable and would defeat any check for it.

if anything what you will see more often is to just extract it manually and run the `squashfs-root/AppRun`, the variable is pretty much just not known, to the point that projects like nvim tell you to extract the appimage and run the `squashfs-root/AppRun` when there is no fuse instead of just setting the variable xd

> If there's no other solution I'm not opposed to adding it, but it should probably be behind an environment variable, something like AISAP_SET_APPIMAGE_EXTRACT_AND_RUN since its usecases are fairly niche

It is only niche if you use a few appimages, but if you want to make it an extra flag that sets it that also works.

The "proper" solution is to use a patched bubblewrap but that's a lot of work, after all if I'm not mistaken using `APPIMAGE_EXTRACT_AND_RUN` has the downsides that it increases the RAM usage of the app and also increases the startup time, but once again right now it is either that or the app just not working.

**Comment by mgord9518** [comment]
@Samueru-sama It's been merged, but alternative solutions should definitely be explored. I think an additional permission asking allowing IPC to request launching other AppImages might be the best long-term

**Pull request merged**
